# Generated by Django 3.0.5 on 2020-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbike', '0002_vehicle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
